src/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Borrower_First_Name__c</fullName>
        <label>Borrower First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrower_Last_Name__c</fullName>
        <label>Borrower Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Level__c</fullName>
        <label>Risk Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Underwriter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Underwriter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Loans</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Loan</label>
    <nameField>
        <displayFormat>LOAN-{00000}</displayFormat>
        <label>Loan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LoanCustomController.cls
public with sharing class LoanCustomController {

    private final Loan__c loan;
    private final List<Loan__C> loans;
    private User  underwriter;
    private Boolean approved;

    public LoanCustomController() {
        loan = [SELECT Id, Amount__c, Approved__c, Borrower_First_Name__c, 
                       Borrower_Last_Name__c, Name, Underwriter__c, Risk_Level__c FROM Loan__c
                   WHERE Id = :ApexPages.currentPage().getParameters().get('id')];
                   
        underwriter = [SELECT Id, Name FROM User Where Id = :loan.Underwriter__c ];
        
        loans = [SELECT Id, Amount__c, Approved__c, Borrower_First_Name__c, 
                       Borrower_Last_Name__c, Name, Underwriter__c, Risk_Level__c FROM Loan__c];
               
    }
    
    public String getLoanName() {
        return loan.Name;
    }

     public String getName() {
        return loan.Borrower_First_Name__c + ' ' + loan.Borrower_Last_Name__c;
    }
    
     public Decimal getAmount() {
        return loan.Amount__c;
    }
   
     public Boolean getApproved() {
        return loan.Approved__c;
    }
 
     public String getUnderwriter() {
       return underwriter.name;
    }
    
     public String getRiskLevel() {
        return loan.Risk_Level__c;
    }
    
     public Boolean getApprovedIndirectRef() {
        approved = loan.Approved__c;
        return approved;
    }

     public List<Loan__c> getLoansList() {
        return loans;
    }

}